EXPERIMENT:
  NAME: "cifar100_res110_res20"
  TAG: "dkd,res110,res20"
  PROJECT: "cifar100_baselines"
  WORKSPACE: ""
  SAVE_DIR: "save/"
  DEVICE: "gpu"
  CKPT_FREQ: 50

DATASET:
  TYPE: "cifar100"
  NUM_WORKERS: 8
  TEST_BATCH_SIZE: 64

DISTILLER:
  TYPE: "DKD"
  TEACHER: "resnet110"
  STUDENT: "resnet20"

SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

DKD:
  CE_WEIGHT: 1.0
  ALPHA: 1.0
  BETA: 8.0
  T: 4.0
  WARMUP: 20

LOG:
  PRINT_FREQ: 100
  SAVE_CHECKPOINT_FREQ: 40
  PREFIX: "./output/dkd"
  WANDB: false
