experiment:
  name: cifar100_res110_res20
  tag: dkd
  project: cifar100_baselines
  workspace: ""
  save_dir: save/
  device: gpu
  ckpt_freq: 50

distiller:
  name: DKD
  T: 4.0
  alpha: 1.0
  beta: 8.0
  warmup: 20

dataset:
  name: cifar100
  root: data
  num_workers: 8

model:
  name: resnet
  teacher:
    depth: 110
    width: 1
    checkpoint: pretrained/resnet110_cifar100.pth
  student:
    depth: 20
    width: 1
    checkpoint: null

solver:
  batch_size: 64
  epochs: 240
  lr: 0.05
  lr_decay_stages: [150, 180, 210]
  lr_decay_rate: 0.1
  weight_decay: 0.0005
  momentum: 0.9
  type: SGD 