EXPERIMENT:
  NAME: "cifar100_vgg13_vgg8"
  TAG: "dkd,vgg13,vgg8"
  PROJECT: "cifar100_baselines"
  WORKSPACE: ""
  SAVE_DIR: "save/"
  DEVICE: "gpu"
  CKPT_FREQ: 50

DISTILLER:
  TYPE: "DKD"
  TEACHER: "vgg13"
  STUDENT: "vgg8"

SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

DKD:
  BETA: 8.0
