EXPERIMENT:
  NAME: ""
  TAG: "grlctdkd,res110,res20"
  PROJECT: "cifar100_baselines"

DISTILLER:
  TYPE: "GRLCTDKD"
  TEACHER: "resnet110"
  STUDENT: "resnet20"

SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 300
  LR: 0.05
  LR_DECAY_STAGES: [150, 200, 250]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

GRLCTDKD:
  INIT_TEMPERATURE: 4.0
  MIN_TEMPERATURE: 1.0
  MAX_TEMPERATURE: 20.0
  GRL_LAMBDA: 0.2
  LEARNING_RATE: 0.0005

DKD:
  CE_WEIGHT: 1.0
  ALPHA: 1.0
  BETA: 15.0
  T: 4.0
  WARMUP: 30

# dataset:
#   name: cifar100
#   root: data
#   num_workers: 8

# model:
#   name: resnet
#   teacher:
#     depth: 110
#     width: 1
#     checkpoint: pretrained/resnet110_cifar100.pth
#   student:
#     depth: 32
#     width: 1
#     checkpoint: null

# solver:
#   batch_size: 64
#   epochs: 240
#   lr: 0.05
#   lr_decay_stages: [150, 180, 210]
#   lr_decay_rate: 0.1
  # weight_decay: 0.0005
  # momentum: 0.9
  # type: SGD 