EXPERIMENT:
  NAME: "cifar100_wrn40_2_wrn16_2"
  TAG: "grlctdkd,wrn40_2,wrn16_2"
  PROJECT: "cifar100_baselines"
  WORKSPACE: ""
  SAVE_DIR: "save/"
  DEVICE: "gpu"
  CKPT_FREQ: 50

DISTILLER:
  TYPE: "GRLCTDKD"
  TEACHER: "wrn40_2"
  STUDENT: "wrn16_2"

SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

GRLCTDKD:
  INIT_TEMPERATURE: 4.0
  GRL_LAMBDA: 0.1
  LEARNING_RATE: 0.0001

DKD:
  CE_WEIGHT: 1.0
  ALPHA: 1.0
  BETA: 8.0
  T: 4.0
  WARMUP: 20

dataset:
  name: cifar100
  root: data
  num_workers: 8

model:
  name: wrn
  teacher:
    depth: 40
    width: 2
    checkpoint: pretrained/wrn40_2_cifar100_acc76.58.pth
  student:
    depth: 16
    width: 2
    checkpoint: null

solver:
  batch_size: 64
  epochs: 240
  lr: 0.05
  lr_decay_stages: [150, 180, 210]
  lr_decay_rate: 0.1
  weight_decay: 0.0005
  momentum: 0.9
  type: SGD 