EXPERIMENT:
  NAME: "cifar100_res110_res20"
  TAG: "ctdkd,res110,res20"
  PROJECT: "cifar100_baselines"
  WORKSPACE: ""
  SAVE_DIR: "save/"
  DEVICE: "gpu"
  CKPT_FREQ: 50

DATASET:
  TYPE: "cifar100"
  NUM_WORKERS: 8
  TEST_BATCH_SIZE: 64

DISTILLER:
  TYPE: "CTDKD"
  TEACHER: "resnet110"
  STUDENT: "resnet20"

SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

CTDKD:
  INIT_TEMPERATURE: 4.0
  MIN_TEMPERATURE: 1.0
  MAX_TEMPERATURE: 10.0
  LEARNING_RATE: 0.0001

LOG:
  PRINT_FREQ: 100
  SAVE_CHECKPOINT_FREQ: 40
  PREFIX: "./output/ctdkd"
  WANDB: false

# dataset:
#   name: cifar100
#   root: data
#   num_workers: 8

# model:
#   name: resnet
#   teacher:
#     depth: 110
#     checkpoint: pretrained/resnet110_cifar100.pth
#   student:
#     depth: 20
#     checkpoint: null

# solver:
#   batch_size: 64
#   epochs: 240
#   lr: 0.05
#   lr_decay_stages: [150, 180, 210]
#   lr_decay_rate: 0.1
#   weight_decay: 0.0005
#   momentum: 0.9
#   type: SGD 
