EXPERIMENT:
  NAME: "cifar100_vgg13_vgg8"
  TAG: "ctdkd,vgg13,vgg8"
  PROJECT: "cifar100_baselines"
  WORKSPACE: ""
  SAVE_DIR: "save/"
  DEVICE: "gpu"
  CKPT_FREQ: 50

DISTILLER:
  TYPE: "CTDKD"
  TEACHER: "vgg13"
  STUDENT: "vgg8"

SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

CTDKD:
  INIT_TEMPERATURE: 4.0
  MIN_TEMPERATURE: 1.0
  MAX_TEMPERATURE: 10.0
  LEARNING_RATE: 0.0001

dataset:
  name: cifar100
  root: data
  num_workers: 8

model:
  name: vgg
  teacher:
    depth: 13
    checkpoint: pretrained/vgg13_cifar100.pth
  student:
    depth: 8
    checkpoint: null

solver:
  batch_size: 64
  epochs: 240
  lr: 0.05
  lr_decay_stages: [150, 180, 210]
  lr_decay_rate: 0.1
  weight_decay: 0.0005
  momentum: 0.9
  type: SGD 